// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyKlFb6kEhIf0FUQdfIoCVLMgnKUOt9zg',
    appId: '1:353447228910:web:fa8c93ad0fb6dc3374caff',
    messagingSenderId: '353447228910',
    projectId: 'smart-campus-health-and-safety',
    authDomain: 'smart-campus-health-and-safety.firebaseapp.com',
    storageBucket: 'smart-campus-health-and-safety.firebasestorage.app',
    measurementId: 'G-XCQBGCZL36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_wRlVOlSKdxn83tNd45Vw0vXFZCwKrk',
    appId: '1:353447228910:android:d3ef7d02fd07e40174caff',
    messagingSenderId: '353447228910',
    projectId: 'smart-campus-health-and-safety',
    storageBucket: 'smart-campus-health-and-safety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDv2SjX4nvrqJfF-k8MGpny9e-lIdEAwI',
    appId: '1:353447228910:ios:16393d68d752802d74caff',
    messagingSenderId: '353447228910',
    projectId: 'smart-campus-health-and-safety',
    storageBucket: 'smart-campus-health-and-safety.firebasestorage.app',
    iosBundleId: 'com.example.mobilProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDv2SjX4nvrqJfF-k8MGpny9e-lIdEAwI',
    appId: '1:353447228910:ios:16393d68d752802d74caff',
    messagingSenderId: '353447228910',
    projectId: 'smart-campus-health-and-safety',
    storageBucket: 'smart-campus-health-and-safety.firebasestorage.app',
    iosBundleId: 'com.example.mobilProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyKlFb6kEhIf0FUQdfIoCVLMgnKUOt9zg',
    appId: '1:353447228910:web:ccbb375a2a4b9b8274caff',
    messagingSenderId: '353447228910',
    projectId: 'smart-campus-health-and-safety',
    authDomain: 'smart-campus-health-and-safety.firebaseapp.com',
    storageBucket: 'smart-campus-health-and-safety.firebasestorage.app',
    measurementId: 'G-Q2VDEL55R8',
  );
}
